name: build
on: [push]

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest
  flake8:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - run: python --version
      - run: pip install flake8
      - run: flake8 app --ignore=E111,E114